### ISSUE TITLE
Podio integration

### ISSUE THREAD

**Issue by lauranoodapera** [Teamweek/tw-button#15]
Have ready that article, but I still cannot get TeamWeek to show up in any
way in Podio. If i highlight some text and left click on it I get a mouse
menu appear that includes "Add to Teamweek" - but I don't get a Teamweek
Button anywhere as shown in your article.

Can you help ?

Thanks
Mike

**Comment by miscer** [comment]
The button cannot find the title if the title field has a different name than "Title" or "Deliverable Title".
