### ISSUE TITLE
Asana integration

### ISSUE THREAD

**Issue by lauranoodapera** [Teamweek/tw-button#16]
desk case: https://toggl.desk.com/agent/case/228911

I downloaded the Teamweek button Chrome extension and tested it once with success. Now I’m trying to use it again and it’s not working… it won’t let me select any user (it just says “Choose” and then has an empty drop down bar when I try and transfer the task from Asana to Teamweek)

Have you had any other user issues with your Teamweek extension button? Is it finicky?

How do I fix this problem?

**Comment by miscer** [comment]
User was signed in with an account with no workspaces
