### ISSUE TITLE
Add support for Google Calendar

### ISSUE THREAD

**Issue by miscer** [Teamweek/tw-button#18]

**Comment by kmcelroy-brown** [comment]
With the support for Google Calendar, would all team members be able to view all tasks in one shared calendar URL? Or would that be associated with the Teamweek Button in Chrome?

**Comment by miscer** [comment]
Hello there! I have just uploaded a new release of the extension, which includes support for Google Calendar. You can find the button when you click on an event:

<img width="419" alt="screen shot 2016-01-29 at 20 12 24" src="https://cloud.githubusercontent.com/assets/1036313/12686935/b4b01978-c6c4-11e5-8428-1044f8495c74.png">

**Comment by kmcelroy-brown** [comment]
Excellent! Are there instructions on Teamweek for how to install this extension?

Thanks!

Kiley

Kiley McElroy-Brown
Research Associate & Project Coordinator
The Concord Consortium
25 Love Lane
Concord, MA 01742
Phone: 978-877-0249
http://www.concord.org

**Comment by miscer** [comment]
You can install it from here: https://chrome.google.com/webstore/detail/teamweek-button/hkccefhopobjcapedjbobimahkpcppnc

More info about the extension: https://support.teamweek.com/teamweek-button-chrome-extension/

If you need any help, send us an email to support@teamweek.com :)

**Comment by kmcelroy-brown** [comment]
Found it! Thanks again!


Kiley McElroy-Brown
Research Associate & Project Coordinator
The Concord Consortium
25 Love Lane
Concord, MA 01742
Phone: 978-877-0249
http://www.concord.org
