### ISSUE TITLE
Zendesk Integration

### ISSUE THREAD

**Issue by miscer** [Teamweek/tw-button#26]
> When looking at a ticket in Zendesk, it would be great to be able to hit the button to add it into team week as we are able to do with ASANA already. Perhaps add the button at the bottom right next to the 'submit ticket as...' button.

**Comment by miscer** [comment]
Desk case 420962

**Comment by herkyl** [comment]
TW button?

**Comment by miscer** [comment]
Yes

**Comment by herkyl** [comment]
Why did you close it :D?
