### ISSUE TITLE
Domains with dashes won't be added

### ISSUE THREAD

**Issue by nea** [Teamweek/tw-button#34]
Hi

Trying to add a custom domain with dashes does not work. After the dash the domain is cut off, e.g. custom-domain.com results in custom.

Best

**Comment by kelonye** [comment]
@nea sorry for the late reply ... did you mean a domain on the task name or?

**Comment by nea** [comment]
Hi @kelonye 

When adding our own custom domain, where we installed Jira, it cuts off with the dash.

So, adding "jira.custom-domain.com" results in "jira.custom"


Best

**Comment by kelonye** [comment]
@nea .. gotcha! .. fixing in a sec

**Comment by kelonye** [comment]
@nea just released patch in v1.10.9
