### ISSUE TITLE
Fetch GitHub milestone due date into task popup state end_date

### ISSUE THREAD

**Issue by garethdhopkins** [Teamweek/tw-button#5]
Do you think it would be advantageous to get the GitHub milestones due date into the popup 'end_date' task state? 

I suppose it depends on the use of the task and whether a particular milestone will be a task from now until the milestone due date.

I am willing to do another PR for it if you think it would be logical, I can see how to pass the value to the popup state and I think I can get the date from the DOM where it is set.

**Comment by herkyl** [comment]
I think it's a good idea :+1:

**Comment by miscer** [comment]
We have plans to add this feature soon, I'll close this once it is implemented.
